# Generated by Django 3.0.7 on 2020-09-10 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=120)),
                ('book_name', models.CharField(max_length=120)),
                ('book_totalpages', models.BigIntegerField()),
                ('book_progress', models.CharField(choices=[('Completed', 'Completed'), ('In Process', 'In Process'), ('Unassigned', 'Unassigned')], default='Unassigned', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('user_role', models.CharField(choices=[('Corrector', 'Corrector'), ('Verifier', 'Verifier')], max_length=9)),
                ('user_email', models.EmailField(max_length=254)),
                ('sets_completed', models.BigIntegerField(default=0)),
                ('pages_completed', models.BigIntegerField(default=0)),
                ('avg_rating', models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1), (0, 0)])),
            ],
        ),
        migrations.CreateModel(
            name='sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setID', models.CharField(max_length=120)),
                ('number', models.IntegerField()),
                ('repoistorylink', models.URLField()),
                ('status', models.CharField(max_length=120)),
                ('version', models.IntegerField()),
                ('deadline', models.DateField()),
                ('assignmentdate', models.DateField(default=django.utils.timezone.now)),
                ('lastsubdate', models.DateField()),
                ('finalsubdate', models.DateField()),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IIT_OpenOCR.book')),
                ('projectmanager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IIT_OpenOCR.manager')),
                ('setCorrector', models.ForeignKey(limit_choices_to={'user_role': 'Correcter'}, on_delete=django.db.models.deletion.PROTECT, related_name='set_corrector', to='IIT_OpenOCR.users')),
                ('setVerifier', models.ForeignKey(limit_choices_to={'user_role': 'Verifier'}, on_delete=django.db.models.deletion.PROTECT, related_name='set_verifier', to='IIT_OpenOCR.users')),
            ],
        ),
    ]
