# Generated by Django 3.1.1 on 2020-09-14 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IIT_OpenOCR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='projectmanager',
            field=models.ForeignKey(limit_choices_to={'user_role': 'Project Manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='set_projectmanager', to='IIT_OpenOCR.users'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='setCorrector',
            field=models.ForeignKey(limit_choices_to={'user_role': 'Corrector'}, on_delete=django.db.models.deletion.PROTECT, related_name='set_corrector', to='IIT_OpenOCR.users'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='setID',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='avg_rating',
            field=models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='github_username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_role',
            field=models.CharField(choices=[('Corrector', 'Corrector'), ('Verifier', 'Verifier'), ('Project Manager', 'Project Manager')], default='Corrector', max_length=15),
        ),
        migrations.DeleteModel(
            name='manager',
        ),
    ]
