# Generated by Django 3.0.7 on 2020-09-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IIT_OpenOCR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='setCorrector',
            field=models.ForeignKey(limit_choices_to={'user_role': 'Corrector'}, on_delete=django.db.models.deletion.PROTECT, related_name='set_corrector', to='IIT_OpenOCR.users'),
        ),
    ]
