# Generated by Django 3.1.1 on 2020-09-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IIT_OpenOCR', '0006_auto_20200925_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logID', models.CharField(max_length=50, unique=True)),
                ('log_setID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IIT_OpenOCR.sets')),
            ],
        ),
    ]
