# Generated by Django 3.1.1 on 2020-10-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIT_OpenOCR', '0007_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('completed', 'completed'), ('In Progress', 'In Progress'), ('Unassigned', 'Unassigned')], default='Unassigned', max_length=50),
        ),
    ]
