# Generated by Django 3.1.1 on 2020-10-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIT_OpenOCR', '0010_auto_20201017_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
