# Generated by Django 3.1.1 on 2020-10-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIT_OpenOCR', '0012_auto_20201019_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_status',
            field=models.CharField(choices=[('Idle', 'Idle'), ('Assigned', 'Assigned')], default='Idle', max_length=80),
        ),
    ]
