# Generated by Django 2.2 on 2020-11-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIT_OpenOCR', '0016_auto_20201104_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='vone_assignmentdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
