# Generated by Django 3.1.1 on 2020-12-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIT_OpenOCR', '0017_auto_20201104_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='v1_rating',
            field=models.IntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='v2_rating',
            field=models.IntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='v3_rating',
            field=models.IntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=0, null=True),
        ),
    ]
