# Generated by Django 3.1.1 on 2020-12-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIT_OpenOCR', '0019_auto_20201202_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='stage',
            field=models.CharField(default='Corrector', max_length=50),
        ),
        migrations.AlterField(
            model_name='sets',
            name='status',
            field=models.CharField(choices=[('Set OCRed', 'Set OCRed'), ('Corrector', 'Corrector'), ('Verifier', 'Verifier'), ('Formatter', 'Formatter'), ('In Process', 'In Process'), ('Unassigned', 'Unassigned'), ('Accepted', 'Accepted')], default='Unassigned', max_length=120),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_role',
            field=models.CharField(choices=[('Corrector', 'Corrector'), ('Verifier', 'Verifier'), ('Project Manager', 'Project Manager'), ('orrctorVerifier', 'corrverifier')], default='Corrector', max_length=15),
        ),
    ]
