# Generated by Django 3.1.1 on 2020-12-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIT_OpenOCR', '0020_auto_20201217_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='stage',
            field=models.CharField(choices=[('Corrector', 'Corrector'), ('Verifier', 'Verifier')], default='Corrector', max_length=50),
        ),
    ]
