# Generated by Django 3.1.1 on 2020-12-20 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IIT_OpenOCR', '0024_auto_20201217_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='bookid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IIT_OpenOCR.book'),
        ),
    ]
