# Generated by Django 3.1.4 on 2020-12-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IIT_OpenOCR', '0025_auto_20201220_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='projectmanager',
            field=models.ForeignKey(limit_choices_to={'user_role': 'Project Manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='set_projectmanager', to='IIT_OpenOCR.users'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='setCorrector',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_role': 'Corrector'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_corrector', to='IIT_OpenOCR.users'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='setVerifier',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_role': 'Verifier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_verifier', to='IIT_OpenOCR.users'),
        ),
    ]
